FROM postgres:15

RUN apt-get update && apt-get install -y cron

RUN mkdir /backups

COPY backup.sh /backup.sh
RUN chmod +x /backup.sh

RUN echo "0 12 * * * /backup.sh >> /var/log/cron.log 2>&1" > /etc/cron.d/backup-cron
RUN chmod 0644 /etc/cron.d/backup-cron

RUN touch /var/log/cron.log

CMD cron && tail -f /var/log/cron.log
