version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: olxparser_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: olxparser_app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: olxparser_backup
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_BACKUP_NAME}
    volumes:
      - postgres_backups:/backups
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
  postgres_backups:
