"""Initial migration

Revision ID: 69cdb564882d
Revises: 
Create Date: 2025-01-22 17:00:36.735622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69cdb564882d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('olx_items', 'lang')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('olx_items', sa.Column('lang', postgresql.ENUM('uk', 'ru', name='lang_enum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
